### ISSUE TITLE
Enable MQ configuration for iqrfapp

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/iqrf-daemon#15]
Similar way as having multiple instances of iqrf-daemon so to enable having of multiple
instances of iqrfapp there is a need to configure MQ local and remote name.

**Comment by fmikulu** [comment]
Implemented at 5b633bd13e7dd7de2630e02eb411aac39ad005d4

**Comment by fmikulu** [comment]
According @spinarr  sugesstion:
The `iqrfapp` seeks configuration file `iqrfapp.json` in:
- working directory
- path: `/etc/iqrf-daemon/`

**Comment by fmikulu** [comment]
Done at b5f51d5a726762411ea9aebad896405527d41d15
