### ISSUE TITLE
Web configuration page

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/iqrf-daemon#19]
Create simple web page for the daemon configuration.

- [x] IQRF interface
- [x] MQTT channels
- [x] MQ channel
- [x] UDP channel
- [x] Tracer file
- [x] Scheduler
- [x] Main config enablers
- [x] Start/Stop/Restart iqrf-daemon service

**Comment by Roman3349** [comment]
Covered by iqrfsdk/iqrf-daemon-webapp#1.
