### ISSUE TITLE
Rename the daemon components

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/iqrf-daemon#26]
Renaming according to component model:
https://github.com/iqrfsdk/iqrf-daemon/blob/master/doc/iqrf-daemon-component-model.png

**Comment by fmikulu** [comment]
Renamed dirs, files, classes and config references

**Comment by fmikulu** [comment]
Forgotten:
$ cat BaseService.json
{
  "Implements": "IClient",

**Comment by fmikulu** [comment]
Done
