### ISSUE TITLE
Compilation error in DaemonController (TRC_START)

### ISSUE THREAD

**Issue by Roman3349** [iqrfsdk/iqrf-daemon#31]
See https://travis-ci.org/iqrfsdk/iqrf-daemon/jobs/223691311#L1596

**Comment by fmikulu** [comment]
see: https://github.com/iqrfsdk/iqrf-daemon/issues/30
Pull rebuild https://github.com/iqrfsdk/cutils as iqrf-daemon depends on it. Travis test would reflect it

**Comment by fmikulu** [comment]
My fault, resolved: Pull rebuild https://github.com/iqrfsdk/cutils 
MSVC didn't complain :-o

**Comment by Roman3349** [comment]
@fmikulu Builds in Travis CI always download external dependencies from branches master or develop (e.g. repository clibdpa). External dependencies always build from source code.

**Comment by Roman3349** [comment]
I restarted failed builds in Travis CI. Fixed.
