### ISSUE TITLE
Solve excessive wdog logging

### ISSUE THREAD

**Issue by fmikulu** [iqrfsdk/iqrf-daemon#36]
There's too much regular trace records from "wdog pet"

**Comment by fmikulu** [comment]
The logging is produced by the Scheduler as the watchdog petting is fired as a task. The cleanest solution is to introduce Logger named channels and enable/disable according the channels and verbosity. The implementation will be done for v2.0.0. The only possibilities for now are to comment out annoying logging for all tasks or to do a hack - conditional logging according the task content. BTW: the tasks are logged  out during processing anyway. @spinarr: what's your opinion?

**Comment by spinarr** [comment]
ok, we can leave it for v2.0.0, it is fine

**Comment by fmikulu** [comment]
Disabled logs from Scheduler, lets see how it's going a8fcd4a69095409e0e91e3227c24268c2ea2ab90
