### ISSUE TITLE
Create parser for ctype "config"

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/iqrf-daemon#40]
ctype: config
type: set
mode: service | operational | forwarding

**Comment by fmikulu** [comment]
Implemented b3b5c0a01ee933b37ec978192e2b58e1e29e6c9
e.g: {"ctype":conf, "type":"mode", "cmd":"operational"}
**Warning: the mode strings starts with lowercase now - valid for iqrfapp as well**
