### ISSUE TITLE
Update JsonDpaRequest examples on wiki

### ISSUE THREAD

**Issue by fmikulu** [iqrfsdk/iqrf-daemon#44]
https://github.com/iqrfsdk/iqrf-daemon/wiki/JsonStructureDpaExamples
delete or update:
https://github.com/iqrfsdk/iqrf-daemon/wiki/JsonStructureDpaQuestions

**Comment by spinarr** [comment]
We have examples here for now:
https://github.com/iqrfsdk/iot-starter-kit/tree/master/workshop/json-messages
