### ISSUE TITLE
Adding ms timestamp into log

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/iqrf-daemon#53]
To have more precise timing in the log file for the analysis.

**Comment by fmikulu** [comment]
Feature is gonna be implemented in cutils repo. Announced here when ready

**Comment by fmikulu** [comment]
Implemented at https://github.com/iqrfsdk/cutils/commit/65880d4efa7d91098b276e85fc28aac6d7c9aed0

It is necessary to rebuild all projects by build scripts

**Comment by fmikulu** [comment]
Added explicit flus() to logger stream at https://github.com/iqrfsdk/cutils/commit/08004ba07a3912e3513291a7ca4e393b401956bd

**Comment by spinarr** [comment]
Very good.
