### ISSUE TITLE
Adding selection of operational mode into JSON config file

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/iqrf-daemon#55]
Can we specify operational mode in the json config file?
During debugging phase could be good to have Forwarding mode enabled right after start.

**Comment by fmikulu** [comment]
See description:
https://github.com/iqrfsdk/iqrf-daemon/wiki/Configuration#main-configuration-file--configjson

It is necessary to merge to other branches if required there, e.g. **origin/feature/ProtocolBridgeClientService**

**Comment by fmikulu** [comment]
Implemented in: 723f3e3c8cb9f5e581e4b27ed56c6fa09beab551

**Comment by spinarr** [comment]
Very good.
