### ISSUE TITLE
Tracer off?

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/iqrf-daemon#66]
Is it possible to turn off the tracer msg completely or having level err is good practice?

**Comment by fmikulu** [comment]
Logging is not too much sophisticated now. The only possibility to controll TRC level is done by config file, e.g:
https://github.com/iqrfsdk/iqrf-daemon/blob/master/daemon/iqrf_startup/configuration/TracerFile.json. The possibilities are:
- err
- war
- inf
- dbg

The level **dbg** is not compiled at all in Release version. Note **dbg** messages are created in Debug even if switch off => test on Release some time critical cases.

I thing the application shall trace at least on **err** level. This level shall be used only if the app is not able to recover and exits itself.
