### ISSUE TITLE
Json parser: ctype conf

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/iqrf-daemon#69]
There is a need to define timeout for ctype:conf?

ubuntu@ubuntu-up-gw01:/IQRF/github/iqrf-daemon/scripts/mq$ ./mq-iqrfapp-switchmode.sh
Sending conf request to change gw mode to operational
14-09-2017 20:04:56.973248 {WAR} getMember()
Throwing std::logic_error: Expected member: name="timeout"
14-09-2017 20:04:56.973474 {WAR} parseCommand()
Caught Cannot parse command: : std::logic_error: Expected member: name="timeout"
cmd="operational"  done
ubuntu@ubuntu-up-gw01:/IQRF/github/iqrf-daemon/scripts/mq$

**Comment by fmikulu** [comment]
Parameter timeout changed to optional
