### ISSUE TITLE
Review current implementation of ctype:conf switching of gw mode

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/iqrf-daemon#70]
Implement ctype:conf according to the definition
https://github.com/iqrfsdk/iqrf-daemon/wiki/JsonStructureConf-v1

**Comment by fmikulu** [comment]
For runtime cfg. update we have only support for **mode** switching (operational/forwarding/service). It make sense to review/update implementation of JSON **mode** msg according the definition.

Does it make sense to develop in scope V1 configuring Trace component?
- level
- file name
- file size

If yes lets make dedicated issue

**Comment by spinarr** [comment]
Only review JSON mode msg:

cmd=operational/forwarding/service

input: "{\"ctype\":\"conf\",\"type\":\"mode\",\"cmd\":\"$cmd\"}"
output: cmd="operational" done

**Comment by fmikulu** [comment]
Implemented b05cfe43b3efa362aba75c789fef1b3f8f3386c3
In feature/ConfParser
@spinarr please try

**Comment by spinarr** [comment]
Now it follows: 

https://github.com/iqrfsdk/iqrf-daemon/wiki/JsonStructureConf-v1
Gateway runtime parameters
There is a mode in which gateway operates.

It is ok.
