### ISSUE TITLE
IQRFAPP gets stuck after sending JSON request

### ISSUE THREAD

**Issue by Roman3349** [iqrfsdk/iqrf-daemon#72]
IQRFAPP gets stuck after sending request "Coordinator get bonded/discovered nodes" in JSON.
Sometimes IQRFAPP return nothing in the stdout.

[Log from iqrf-daemon](https://github.com/iqrfsdk/iqrf-daemon/files/1306971/iqrf-daemon-log.txt)

**Comment by fmikulu** [comment]
@Roman3349 please retest with the latest iqrfapp

**Comment by Roman3349** [comment]
Fixed
