### ISSUE TITLE
Building IQRF daemon from the source

### ISSUE THREAD

**Issue by mienkofax** [iqrfsdk/iqrf-daemon#73]
Updating of tutorial for IQRF daemon building on the basis of last changes in source code.

[Building IQRF daemon from the source](https://github.com/iqrfsdk/iqrf-daemon/blob/master/BUILD.md)

**Comment by fmikulu** [comment]
Can you be more specific what is the problem?

**Comment by spinarr** [comment]
I know what is needed, working on it ...

**Comment by mienkofax** [comment]
@fmikulu The building manual was not changed in the last commits. However, installation scripts were removed/edited in the last commits.

@spinarr Thanks for repair.

**Comment by fmikulu** [comment]
OK, can we close it then?

**Comment by spinarr** [comment]
https://github.com/iqrfsdk/iqrf-daemon/commit/2057e19a701eb721fe02f663d3d6f5f3d8312388
