### ISSUE TITLE
JsonDpaResponse raw-hdp must mirror "rdata" item

### ISSUE THREAD

**Issue by fmikulu** [iqrfsdk/iqrf-daemon#88]
The JSON item "rdata" is not added if Dpa rdata is empty

**Comment by fmikulu** [comment]
Fixed by c9e77efe7571d3cf30a410ac3ec8fe055defdb95

**Comment by spinarr** [comment]
rdata should go after dpaval ...

{
    "ctype": "dpa",
    "type": "raw-hdp",
    "msgid": "1",
    "timeout": 1000,
    "nadr": "01",
    "pnum": "06",
    "pcmd": "83",
    "hwpid": "0002",
    "rcode": "00",
    "rdata": "",
    "dpaval": "6a",
    "status": "STATUS_NO_ERROR"
}

**Comment by fmikulu** [comment]
Well, no problem. On the other hand it doesn't matter from JSON POV as it is intended for machine reading.

**Comment by spinarr** [comment]
tested, ok
