### ISSUE TITLE
Double check watchdog function - takes 100% of CPU time

### ISSUE THREAD

**Issue by fmikulu** [iqrfsdk/iqrf-daemon#9]
Imported from: https://iqrfsdk.atlassian.net/browse/SDKST-35?filter=-1

**Comment by fmikulu** [comment]
Corrected in 642c30f8071ee6b7fad6345867c44f60909ed785
Please verify or report to colleague who reported the problem if it is fine

**Comment by spinarr** [comment]
Reported

**Comment by spinarr** [comment]
ubuntu@ubuntu-up-gw01:~/IQRF/iqrf-daemon/daemon/iqrf_startup/configuration$ ps -p 4795 -o %cpu,%mem,cmd
%CPU %MEM CMD
 0.6  0.6 /usr/bin/iqrf_startup /etc/iqrf-daemon/config.json

**Comment by spinarr** [comment]
pi@raspberrypi:~ $ ps -p 31918 -o %cpu,%mem,cmd
%CPU %MEM CMD
 0.6  0.5 /usr/bin/iqrf_startup /etc/iqrf-daemon/config.json
