### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by spinarr** [iqrfsdk/iqrf-daemon#93]
59. minute is missed in every hour using this rule:

 {
            "time": "* */1 * * * * *",
            "service": "BaseServiceForMQTTAzure",
            "message": {
                "ctype": "dpa",
                "type": "raw-hdp",                                                                                                          
                "msgid": "",
                "timeout": 6000,
                "nadr": "00",
                "pnum": "0D",
                "pcmd": "00",
                "hwpid": "FFFF",
                "rcode": "",
                "rdata": "10.5E.00.00.00",
                "request": "",
                "request_ts": "",
                "confirmation": "",
                "confirmation_ts": "",
                "response": "",
                "response_ts": ""
            }
  }

**Comment by fmikulu** [comment]
The bug is corrected in master
